spring.application.name=qaryati
spring.datasource.url=jdbc:postgresql://localhost:5544/qaryati
spring.datasource.username=${DB_USERNAME:qaryati_user}
spring.datasource.password=${DB_PASSWORD:change_me_locally}